import { useRouter } from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import RouterComponent from '../components/RouterComponent';

import { useEffect, useContext, useState } from 'react';
import { MenuContext } from './_app.js';
import MainTop from '../components/Main/MainTop';
import MainAbout from '../components/Main/MainAbout';
import MainTopProducts from '../components/Main/MainTopProducts';
import MainLatestProjects from '../components/Main/MainLatestProjects';
import MainQualityIndicators from '../components/Main/MainQualityIndicators';
import MainResponses from '../components/Main/MainResponses';
import MainLatestNews from '../components/Main/MainLatestNews';
import Partners from '../components/Partners';

export default function Main(props) {
  const router = useRouter();
  let { lang } = router.query;

  const [activeLang, setActiveLang] = useState('uz');
  useEffect(() => {
    if (!lang) {
      setActiveLang(localStorage.getItem('lang'));
    } else {
      setActiveLang(lang);
    }
  }, []);

  const setActiveMenuLink = useContext(MenuContext);

  useEffect(() => {
    setActiveMenuLink(1);
    window.scrollTo({top: 0, left: 0, behavior: "smooth"});
  }, [])

  return (
    <RouterComponent lang={activeLang}>
      <div className="main-page">
        <MainTop maintitle={props.maintitle} />
        <MainAbout />
        <MainTopProducts />
        <MainLatestProjects />
        <MainQualityIndicators />
        <MainResponses />
        <MainLatestNews />
        <Partners titleSmall="main.collaboration" titleBig="main.ourPartners" />
      </div>


      {/*<div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.js</code>
          </p>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/master/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>
      </div>*/}
    </RouterComponent>
  )
}

export function getStaticPaths() {
  return {
    fallback: true,
    paths: [
      {
        params: {lang: 'uz'}
      },
      {
        params: {lang: 'ru'}
      },
      {
        params: {lang: 'en'}
      }
    ]
  }
}

export async function getStaticProps() {
  return {
    props: {
      maintitle: 'POLIMER GROUP ASIA '
    }
  }
}